In [1]:
# Import libraries
import numpy as np
import pandas as pd

In [2]:
# Load dataset
df = pd.read_csv('customer.csv')

In [3]:
# Check data
print(df.head())


   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No


In [4]:

# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df[['review', 'education']],
    df['purchased'],      # agar column name purchased hai
    test_size=0.2,
    random_state=42
)


What it does:

Splits the dataset into training and testing sets.
X contains input features (review, education).
y contains the target variable (purchased).
80% data is used for training.
20% data is used for testing.

Why?

To evaluate the model on unseen data.

In [5]:
# Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[
        ['Poor', 'Average', 'Good'],
        ['School', 'UG', 'PG']
    ]
)

Ordinal Encoding converts ordered categorical values into numerical values.

Mappings:

Review:

Poor    → 0
Average → 1
Good    → 2

Education:

School → 0
UG     → 1
PG     → 2

Why?

Machine learning algorithms work with numbers, not text.

In [6]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)


In [7]:
print("Encoded X_train:")
print(X_train[:5])

Encoded X_train:
[[0. 0.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [2. 2.]]


In [14]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [17]:
print("\nClasses:")
print(le.classes_)


Classes:
[0 1]


In [18]:
print("\nEncoded y_train:")
print(y_train[:5])


Encoded y_train:
[0 0 1 0 0]


In [ ]:
print(X_train[:5])
print(y_train[:5])

[[0. 0.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [2. 2.]]
[0 0 1 0 0]
